using System;using System.Collections.Generic;using System.IO;using System.Text.Json;using Elemental.Presentation.DistantScenery;using Unity.Mathematics;
class Program{
static void Need(bool value,string message){if(!value)throw new Exception(message);}
static void Published(RockShapeData shape,string name){shape.NormalizeHeight();float minimum=float.PositiveInfinity;foreach(var part in shape.Parts)foreach(var face in part.Solid.Faces){int start=RockPolyhedron.FanStart(face);var origin=part.Point(face.Points[start]);for(int i=1;i<face.Points.Count-1;i++){var cross=math.cross(part.Point(face.Points[(start+i)%face.Points.Count])-origin,part.Point(face.Points[(start+i+1)%face.Points.Count])-origin);minimum=math.min(minimum,math.lengthsq(cross));}}Need(minimum>1e-12f,"Published sliver "+name+" min "+minimum);}
static int Main(string[] args){try{if(args.Length>0){Published(RockShapeBuilder.Pillar(4471,false,RockShapeSettings.Default),"4471");Published(RockShapeBuilder.Group(991,3,true,1,false,RockShapeSettings.Default),"991");Console.WriteLine("Exact legacy normalized4471+991 PASS");return 0;}Run();return 0;}catch(Exception error){Console.WriteLine(error);return 1;}}static void Run(){var watch=System.Diagnostics.Stopwatch.StartNew();int highMax=0,lowMax=0,reject=0,cases=0;var previews=new List<object>();
for(int seed=0;seed<48;seed++)foreach(bool low in new[]{false,true}){var shape=RockShapeBuilder.Pillar(seed*7381,low,RockShapeSettings.Default);Need(shape.Validate(out double v),"Invalid pillar "+seed);if(low)lowMax=Math.Max(lowMax,shape.TriangleCount);else highMax=Math.Max(highMax,shape.TriangleCount);reject+=shape.RejectedCuts;Published(shape,"pillar "+seed+" low "+low);cases++;}
for(int seed=0;seed<48;seed++)for(int family=0;family<6;family++){int key=seed*7381+family*131;bool floating=family>=3;int count=floating?2+family%4:3+family;Console.WriteLine($"GROUP {seed} {family} key={key}");var high=RockShapeBuilder.Group(key,count,floating,family,false,RockShapeSettings.Default);var low=RockShapeBuilder.Group(key,count,floating,family,true,RockShapeSettings.Default);Need(high.Validate(out _)&&low.Validate(out _),"Invalid group "+seed);Need(high.Parts.Count==low.Parts.Count,"LOD count");for(int i=0;i<high.Parts.Count;i++){Need(math.all(high.Parts[i].Translation==low.Parts[i].Translation),"LOD translation");Need(math.all(high.Parts[i].Scale==low.Parts[i].Scale),"LOD scale");Need(math.all(high.Parts[i].Rotation.value==low.Parts[i].Rotation.value),"LOD rotation");}high.Bounds(out var hmin,out var hmax);low.Bounds(out var lmin,out var lmax);Need(math.all(hmin>=lmin-.0001f)&&math.all(hmax<=lmax+.0001f),"LOD containment");Need(math.cmax(math.abs((hmax-hmin)-(lmax-lmin)))<.08f,"LOD bounds");Published(high,"group "+seed+" family "+family);Published(low,"low group "+seed+" family "+family);cases+=2;}
for(int seed=0;seed<12;seed++){var shape=RockShapeBuilder.Pillar(13771+seed*1013,false,RockShapeSettings.Default);var faces=new List<object>();foreach(var part in shape.Parts)foreach(var face in part.Solid.Faces){var points=new List<float[]>();foreach(var point in face.Points){var q=part.Point(point);points.Add(new[]{q.x,q.y,q.z});}faces.Add(points);}previews.Add(new{seed=13771+seed*1013,faces,triangles=shape.TriangleCount});}
File.WriteAllText("preview-data.json",JsonSerializer.Serialize(previews));var report=new{cases,highMax,lowMax,rejectedOptionalCuts=reject,elapsedMs=watch.ElapsedMilliseconds,status="PASS"};File.WriteAllText("report.json",JsonSerializer.Serialize(report));Console.WriteLine(JsonSerializer.Serialize(report));}}
