using System;
using System.Collections.Generic;
using System.Reflection;
using Elemental.Presentation.Animation;
using Elemental.Presentation.Camera;
using Elemental.Runtime.Characters;
using Elemental.Runtime.World;
using Elemental.Simulation.Bending;
using Elemental.Simulation.Characters;
using Unity.Mathematics;
using UnityEditor;
using UnityEngine;
using UnityEngine.SceneManagement;
using Object=UnityEngine.Object;
namespace Elemental.Authoring.Editor{
[InitializeOnLoad]public static class AnimationVisualQaDriver{
 const string Scene="Assets/Elemental/Content/Scenes/EarthCoreSlice.unity",Key="Elemental.AnimationVisualQa.Armed";
 static readonly List<A> a=new();static readonly List<Object> made=new();static readonly Dictionary<Behaviour,bool> off=new();
 static S s;static double at,limit,frameUntil;static bool run,pending,clockHeld,cameraFramingAdjusted;static float savedScale,savedTrackingHeight,savedNeutralPitch;static EarthCinemachineCameraController cameraController;static FieldInfo trackingHeightField,neutralPitchField;
 static AnimationVisualQaDriver(){EditorApplication.playModeStateChanged-=Play;EditorApplication.playModeStateChanged+=Play;}
 [MenuItem("Elemental/QA/Capture Final Animation Actual Game Matrix")]public static void Run(){if(run||SessionState.GetBool(Key,false))throw new Exception("Already running");if(SceneManager.GetActiveScene().path!=Scene)throw new Exception("Open EarthCoreSlice");SessionState.SetBool(Key,true);if(Application.isPlaying)Start();else EditorApplication.isPlaying=true;}
 public static void Abort(){if(run)End("Aborted");}
 static void Play(PlayModeStateChange x){if(!SessionState.GetBool(Key,false))return;if(x==PlayModeStateChange.EnteredPlayMode)Start();else if(x==PlayModeStateChange.ExitingPlayMode&&run)End("Play exited");}
 static void Start(){if(run)return;run=true;s=S.Ready;limit=Now+130;EditorApplication.update+=Tick;AssemblyReloadEvents.beforeAssemblyReload+=Abort;}
 static void Tick(){if(!run)return;try{if(Now>limit)throw new TimeoutException("Timeout "+s);if(s==S.Ready){var g=Object.FindAnyObjectByType<EarthSceneReadinessGate>(FindObjectsInactive.Include);if(g==null||g.Failed)throw new Exception("Readiness failed");if(!g.IsReady)return;Setup();Go(S.Idle,2f);return;}if(pending){if(!AnimationVisualQaCaptureSession.IsReadyForNext)return;pending=false;if(clockHeld){Time.timeScale=savedScale;clockHeld=false;}After();return;}Step();}catch(Exception e){End(e.ToString());}}
 static void Setup(){var sc=SceneManager.GetActiveScene();var f=typeof(PlanetMotor).GetField("inputSourceBehaviour",BindingFlags.Instance|BindingFlags.NonPublic);foreach(var p in Object.FindObjectsByType<HumanoidCharacterPresentation>(FindObjectsInactive.Include,FindObjectsSortMode.None)){if(p.gameObject.scene!=sc)continue;var m=p.GetComponentInParent<PlanetMotor>();if(m==null)continue;var b=m.GetComponent<Rigidbody>();var i=m.gameObject.AddComponent<QInput>();var up=m.LocalUp.normalized;a.Add(new A{p=p,m=m,b=b,i=i,old=f?.GetValue(m)as MonoBehaviour,pos=b.position,rot=b.rotation,vel=b.linearVelocity,ang=b.angularVelocity,foot=Vector3.Dot(b.position-m.SupportFeetPoint(up),up)});m.ConfigureInputSource(i);}if(a.Count!=2)throw new Exception("Expected 2 humanoids; "+a.Count);foreach(var x in Object.FindObjectsByType<Behaviour>(FindObjectsInactive.Include,FindObjectsSortMode.None))if(x.gameObject.scene==sc&&(x is EarthMvpBotController||x is EarthMvpDuelController)){off[x]=x.enabled;x.enabled=false;}foreach(var t in Object.FindObjectsByType<EarthCharacterImpactTarget>(FindObjectsInactive.Include,FindObjectsSortMode.None))if(t.gameObject.scene==sc)t.SuppressImpacts(120);AdjustCameraFraming();Surface();AnimationVisualQaCaptureSession.Begin();limit=Now+100;}
 static void Step(){switch(s){
 case S.Idle:if(Wait)Cap("idle");break;case S.Walk:Move(0,.55f);if(Wait)Cap("walk");break;case S.Stop:Move(0,0);if(Wait)Cap("stop");break;
 case S.Left:Move(-1,0);if(Wait)Cap("turn-left");break;case S.Right:Move(1,0);if(Wait)Cap("turn-right");break;
 case S.Build:if(Wait){StageAt(-2.2f);Go(S.Approach,1.1f);}break;case S.Approach:Move(0,.4f);if(a[0].track.InverseTransformPoint(a[0].m.SupportFeetPoint(a[0].m.LocalUp.normalized)).z>-.15f){Move(0,0);Go(S.Pit,.5f);}break;
 case S.Pit:if(Wait)Cap("uneven-pit");break;case S.SlopeWalk:Move(0,.45f);if(a[0].track.InverseTransformPoint(a[0].b.position).z>1){Move(0,0);Go(S.Slope,.35f);}break;
 case S.Slope:if(Wait)Cap("uneven-slope");break;case S.PreMantle:if(Wait){StageAt(-2.2f);Ledges();Move(0,1);Go(S.Mantle,0);}break;case S.Mantle:Mantle();break;
 case S.MagicBegin:Magic();Go(S.MagicStart,.06f);break;case S.MagicStart:if(Wait)Cap("magic-start");break;case S.MagicSample:if(Wait)Cap("magic-sample");break;
 case S.MagicRecovery:if(Wait)Cap("magic-recovery");break;case S.Done:End(null);break;}}
 static void After(){switch(s){case S.Idle:Go(S.Walk,.5f);break;case S.Walk:Go(S.Stop,.45f);break;case S.Stop:Go(S.Left,.25f);break;case S.Left:Move(0,0);Go(S.Right,.4f);break;case S.Right:Move(0,0);Go(S.Build,.2f);break;case S.Pit:Go(S.SlopeWalk,0);break;case S.Slope:Go(S.PreMantle,.1f);break;case S.MagicStart:Go(S.MagicSample,.18f);break;case S.MagicSample:Go(S.MagicRecovery,1);break;case S.MagicRecovery:Go(S.Done,0);break;}}
 static void Mantle(){var x=a.Find(v=>v.p.GetComponent<EarthCharacterPoseController>()!=null)??a[0];if(x.m.IsMantling&&x.seen.Count==0)Move(0,0);var ph=x.m.MantlePhase;string n=ph switch{EarthMantlePhase.Reach=>"mantle-reach",EarthMantlePhase.Raise=>"mantle-raise",EarthMantlePhase.Transfer=>"mantle-transfer",EarthMantlePhase.Settle=>"mantle-settle",_=>null};if(n!=null&&!x.seen.Contains(ph)&&Cap(n))x.seen.Add(ph);if(!x.m.IsMantling&&x.seen.Count>0){if(x.seen.Count<4)throw new Exception("Missed mantle phases "+x.seen.Count);Move(0,0);Go(S.MagicBegin,.5f);}}
 static bool Cap(string n){if(!AnimationVisualQaCaptureSession.TryValidateFraming(out var why)){if(frameUntil<=0){frameUntil=Now+3;(Object.FindAnyObjectByType<EarthCinemachineCameraController>(FindObjectsInactive.Include))?.SnapToTarget();}if(Now>=frameUntil)throw new Exception(n+" framing failed: "+why);return false;}frameUntil=0;if(n.StartsWith("mantle",StringComparison.Ordinal)||n.StartsWith("magic",StringComparison.Ordinal)){savedScale=Time.timeScale;Time.timeScale=0;clockHeld=true;}AnimationVisualQaCaptureSession.Capture(n,n);pending=true;return true;}
 static void Surface(){var z=a[0];var up=z.m.LocalUp.normalized;var fw=Vector3.ProjectOnPlane(z.m.FacingForward,up).normalized;var rt=Vector3.Cross(up,fw).normalized;var mat=Mat();for(int q=0;q<a.Count;q++){var x=a[q];var go=new GameObject("QA uneven "+q);made.Add(go);SceneManager.MoveGameObjectToScene(go,SceneManager.GetActiveScene());go.transform.SetPositionAndRotation(z.m.SupportFeetPoint(up)+up*22+rt*(q==0?-.85f:.85f),Quaternion.LookRotation(fw,up));x.track=go.transform;Layer(go,x.m);var me=Track();made.Add(me);go.AddComponent<MeshCollider>().sharedMesh=me;go.AddComponent<MeshFilter>().sharedMesh=me;go.AddComponent<MeshRenderer>().sharedMaterial=mat;x.m.CancelMantle();if(!x.b.isKinematic){x.b.linearVelocity=Vector3.zero;x.b.angularVelocity=Vector3.zero;}x.b.position=go.transform.TransformPoint(new Vector3(0,H(0,-2.2f),-2.2f))+up*x.foot;x.b.rotation=Quaternion.LookRotation(fw,up);x.p.FootContactController?.InvalidateBasePose();}Physics.SyncTransforms();(Object.FindAnyObjectByType<EarthCinemachineCameraController>(FindObjectsInactive.Include))?.SnapToTarget();}
 static void StageAt(float z){Move(0,0);foreach(var x in a){var up=x.track.up;x.m.CancelMantle();x.b.position=x.track.TransformPoint(new Vector3(0,H(0,z),z))+up*x.foot;x.b.rotation=Quaternion.LookRotation(x.track.forward,up);if(!x.b.isKinematic){x.b.linearVelocity=Vector3.zero;x.b.angularVelocity=Vector3.zero;}x.p.FootContactController?.InvalidateBasePose();}Physics.SyncTransforms();(Object.FindAnyObjectByType<EarthCinemachineCameraController>(FindObjectsInactive.Include))?.SnapToTarget();}
 static void Ledges(){foreach(var x in a){var up=x.m.LocalUp.normalized;var fw=Vector3.ProjectOnPlane(x.m.FacingForward,up).normalized;var go=GameObject.CreatePrimitive(PrimitiveType.Cube);made.Add(go);go.name="QA mantle ledge";SceneManager.MoveGameObjectToScene(go,SceneManager.GetActiveScene());go.transform.SetPositionAndRotation(x.m.SupportFeetPoint(up)+fw*2.3f+up*.2f,Quaternion.LookRotation(fw,up));go.transform.localScale=new Vector3(4f,1.4f,3f);go.GetComponent<Renderer>().sharedMaterial=Mat();Layer(go,x.m);x.m.CancelMantle();x.seen.Clear();}Physics.SyncTransforms();}
 static void Magic(){foreach(var x in a){var p=x.p.GetComponent<EarthCharacterPoseController>();if(p==null)continue;var m=typeof(EarthCharacterPoseController).GetMethod("BeginAuthoritative",BindingFlags.Instance|BindingFlags.NonPublic);m?.Invoke(p,new object[]{EarthTechniqueKind.Wall,EarthTechniqueId.RaiseWall,p.PresentationTick,x.p.transform.position+x.p.transform.forward*3,80f,4f});}}
 static void Move(float x,float y){foreach(var z in a)z.i.move=new float2(x,y);}static bool Wait=>Now>=at;static double Now=>Time.realtimeSinceStartupAsDouble;static void Go(S x,float d){s=x;at=Now+d;frameUntil=0;}
 static void Bodies(){Move(0,0);foreach(var x in a){x.m.CancelMantle();x.b.position=x.pos;x.b.rotation=x.rot;if(!x.b.isKinematic){x.b.linearVelocity=Vector3.zero;x.b.angularVelocity=Vector3.zero;}x.p.FootContactController?.InvalidateBasePose();}foreach(var x in made)if(x!=null)Object.Destroy(x);made.Clear();Physics.SyncTransforms();}
 static void End(string e){run=false;EditorApplication.update-=Tick;AssemblyReloadEvents.beforeAssemblyReload-=Abort;SessionState.EraseBool(Key);if(clockHeld){Time.timeScale=savedScale;clockHeld=false;}try{if(AnimationVisualQaCaptureSession.IsRunning){if(e==null)AnimationVisualQaCaptureSession.Finish();else AnimationVisualQaCaptureSession.AbortWithError(e);}Bodies();foreach(var x in a){if(!x.b.isKinematic){x.b.linearVelocity=x.vel;x.b.angularVelocity=x.ang;}x.m.ConfigureInputSource(x.old);if(x.i!=null)Object.Destroy(x.i);}foreach(var x in off)if(x.Key!=null)x.Key.enabled=x.Value;}finally{RestoreCameraFraming();a.Clear();off.Clear();made.Clear();}Debug.Log("[AnimationVisualQaDriver] "+(e??AnimationVisualQaCaptureSession.OutputFolder));if(Application.isPlaying&&EditorApplication.isPlaying)EditorApplication.delayCall+=StopAfter;}
 static void AdjustCameraFraming(){cameraController=Object.FindAnyObjectByType<EarthCinemachineCameraController>(FindObjectsInactive.Include);if(cameraController==null)throw new Exception("Production Cinemachine controller missing");trackingHeightField=typeof(EarthCinemachineCameraController).GetField("trackingHeight",BindingFlags.Instance|BindingFlags.NonPublic);neutralPitchField=typeof(EarthCinemachineCameraController).GetField("neutralPitch",BindingFlags.Instance|BindingFlags.NonPublic);if(trackingHeightField==null||neutralPitchField==null)throw new Exception("Production camera composition fields unavailable");savedTrackingHeight=(float)trackingHeightField.GetValue(cameraController);savedNeutralPitch=(float)neutralPitchField.GetValue(cameraController);trackingHeightField.SetValue(cameraController,-.55f);neutralPitchField.SetValue(cameraController,7f);cameraFramingAdjusted=true;cameraController.SnapToTarget();}
 static void RestoreCameraFraming(){if(cameraFramingAdjusted&&cameraController!=null){trackingHeightField?.SetValue(cameraController,savedTrackingHeight);neutralPitchField?.SetValue(cameraController,savedNeutralPitch);cameraController.SnapToTarget();}cameraFramingAdjusted=false;cameraController=null;trackingHeightField=null;neutralPitchField=null;}
 static void StopAfter(){EditorApplication.delayCall-=StopAfter;if(Application.isPlaying)EditorApplication.isPlaying=false;}
 static void Layer(GameObject g,PlanetMotor m){for(int n=0;n<32;n++)if((m.GroundMask.value&(1<<n))!=0){g.layer=n;break;}}
 static Material Mat(){foreach(var r in Object.FindObjectsByType<Renderer>(FindObjectsInactive.Include,FindObjectsSortMode.None))if(r.sharedMaterial!=null&&r.sharedMaterial.name.Contains("ArenaSandstone",StringComparison.OrdinalIgnoreCase))return r.sharedMaterial;throw new Exception("Arena material missing");}
 static float H(float x,float z)=>-(x*x+z*z)/40f+.11f*Mathf.Exp(-Mathf.Pow((z+.7f)/.36f,2))-.13f*Mathf.Exp(-Mathf.Pow((z-.1f)/.3f,2))*Mathf.Exp(-Mathf.Pow((x+.14f)/.42f,2))+.13f*Mathf.SmoothStep(0,1,Mathf.InverseLerp(.45f,1.25f,z));
 static Mesh Track(){const int nx=24,nz=72;var v=new Vector3[(nx+1)*(nz+1)];var t=new int[nx*nz*6];for(int z=0;z<=nz;z++)for(int x=0;x<=nx;x++){float px=Mathf.Lerp(-1.1f,1.1f,x/(float)nx),pz=Mathf.Lerp(-3,3,z/(float)nz);v[z*(nx+1)+x]=new Vector3(px,H(px,pz),pz);}int k=0;for(int z=0;z<nz;z++)for(int x=0;x<nx;x++){int c=z*(nx+1)+x,d=c+nx+1;t[k++]=c;t[k++]=d;t[k++]=c+1;t[k++]=c+1;t[k++]=d;t[k++]=d+1;}var m=new Mesh{name="QA pit slope",vertices=v,triangles=t};m.RecalculateNormals();m.RecalculateBounds();return m;}
 sealed class QInput:MonoBehaviour,IPlanetMotorInputSource{public float2 move;public PlanetMotorCommand SampleCommand(uint tick)=>new(tick,move,false);}
 sealed class A{public HumanoidCharacterPresentation p;public PlanetMotor m;public Rigidbody b;public QInput i;public MonoBehaviour old;public Vector3 pos,vel,ang;public Quaternion rot;public Transform track;public float foot;public readonly HashSet<EarthMantlePhase> seen=new();}
 enum S{Ready,Idle,Walk,Stop,Left,Right,Build,Approach,Pit,SlopeWalk,Slope,PreMantle,Mantle,MagicBegin,MagicStart,MagicSample,MagicRecovery,Done}
}}
