from pathlib import Path
p=Path('Assets/Elemental/Presentation/UI/CinematicMenuCamera.cs');s=p.read_text(encoding='utf-8-sig').replace('        [SerializeField] private CinemachineCamera gameplayCamera;','        [SerializeField] private CinemachineCamera gameplayCamera;\n        [SerializeField] private EarthCinemachineCameraController gameplayController;');s=s.replace('CinemachineCamera gameplay = null)','CinemachineCamera gameplay = null, EarthCinemachineCameraController controller = null)');s=s.replace('gameplayCamera = gameplay; _opponentMotor','gameplayCamera = gameplay; gameplayController = controller; _opponentMotor');s=s.replace('                _dollyEndState = gameplayCamera.State; _dollyEndCaptured = true;','                gameplayController?.SnapToTarget();\n                gameplayCamera.PreviousStateIsValid = false;\n                gameplayCamera.UpdateCameraState(motor != null ? motor.LocalUp : actor.up, -1f);\n                _dollyEndState = gameplayCamera.State; _dollyEndCaptured = true;');s=s.replace('            Quaternion rotation = Quaternion.Slerp(Quaternion.LookRotation(_dollyCenter - position, up), _dollyEndState.GetFinalOrientation(), align);','''            Quaternion endRotation = _dollyEndState.GetFinalOrientation();
            Vector3 gameplayAim = _dollyEndState.GetFinalPosition() + endRotation * Vector3.forward * Mathf.Max(1f, endOffset.magnitude);
            Vector3 aim = Vector3.Lerp(_dollyCenter, gameplayAim, align);
            Quaternion rotation = Quaternion.LookRotation(aim - position, Vector3.Slerp(up, endRotation * Vector3.up, align));''');p.write_text(s,encoding='utf-8')
p=Path('Assets/Elemental/Authoring/Editor/AlphaFrontendSetup.cs');s=p.read_text(encoding='utf-8-sig').replace('duel.BotTransform, cameraController.VirtualCamera);','duel.BotTransform, cameraController.VirtualCamera, cameraController);');p.write_text(s,encoding='utf-8')
p=Path('BuildReports/AlphaImplementation/Stage2Pending/Assets/Elemental/NetworkingStage2/EarthOnlinePresentationBridge.cs');s=p.read_text(encoding='utf-8-sig').replace('actorOne.OriginalDofSecondary, view.GameplayCamera);','actorOne.OriginalDofSecondary, view.GameplayCamera, view.Controller);');p.write_text(s,encoding='utf-8')
p=Path('Assets/Elemental/Tests/PlayMode/AlphaFrontendPlayTests.cs');s=p.read_text(encoding='utf-8-sig').replace('                    yield return Capture($"Countdown-{digit}.png");','''                    File.AppendAllText(Folder + "/countdown-camera.txt", $"digit={digit} actualFov={_camera.fieldOfView} physical={_camera.usePhysicalProperties} focal={_camera.focalLength} distance={Vector3.Distance(_camera.transform.position,menu.SubjectCenter)} pos={_camera.transform.position} center={menu.SubjectCenter}\\n");
                    if (digit == "4" && !flow.Preferences.ReducedMotion) Assert.That(_camera.focalLength, Is.GreaterThan(130f));
                    foreach (var subject in new[] { duel.PlayerTransform, duel.BotTransform })
                    {
                        Vector3 screen = _camera.WorldToViewportPoint(subject.position);
                        Assert.That(screen.x, Is.InRange(.03f, .97f), digit + ": fighter left countdown frame.");
                        Assert.That(screen.y, Is.InRange(.03f, .97f), digit + ": fighter left countdown frame.");
                    }
                    yield return Capture($"Countdown-{digit}.png");''');p.write_text(s,encoding='utf-8')
