from pathlib import Path
p=Path('Docs/ALPHA_SETTINGS_AND_ACCEPTANCE.md');s=p.read_text(encoding='utf-8-sig')
s=s.replace('| Menu/HUD fonts, sizes, palette, timings, sounds |','| Menu/HUD fonts, sizes, palette, timings, sounds; **Elemental > UI > Select In-Game HUD Theme** |')
s=s.replace('FOV 38°, 0.85 s transition','FOV 38°; countdown side azimuth 85°, elevation 18°; 4–3–2–1 with final 1.5 s camera flight')
s=s.replace('- AlphaFrontendPlay: 1/1 at 16:02:40 UTC, Main/Settings/Combat at 16:9, 16:10 and 21:9, keyboard entry, repeated transition, actual camera/clock restoration. Preserved 38.1 px timer and 51.5 px scores verified.','- AlphaFrontendPlay: 1/1 at 17:08:19 UTC. Main/Settings/Combat/Pause at 16:9, 16:10 and 21:9; actual 4–3–2–1 without advancing match time; pause freezes position/time, resumes health/time without restarting, Settings returns to Pause, End Match returns Main. All HUD text explicitly uses Varose; 38.1 px timer and 51.5 px scores retained. Countdown/Pause/Combat frames inspected.')
s=s.replace('- AlphaPhysicsRhythmEdit: 41/41 at 16:23:28 UTC. Actual player ten-cycle mean ratio 0.999395; bot settled-foot acceptance is still being repaired. Do not mark locomotion accepted yet.','- AlphaPhysicsRhythmEdit: 42/42 at 16:44:01 UTC; AlphaCadencePlay 2/2 at 16:51:11 UTC. Ten-cycle actual/requested ratios player 0.999438, bot 0.999798, both settled feet accepted. Slope clearance and visible turn completion remain separate unresolved gates.')
s=s.replace('remaining cadence check, final build and commit','remaining slope/turn/physics steering, final build and commit')
s += '\nLatest steering: wall-only bevel target saved 0.0525 m (3.5× former 0.015 m); shared whole/cracked/ejected cell geometry. Visual destruction/repair verification pending. Sequential repair, crushing heavy falls and removing Earth character-body control are in progress.\n'
p.write_text(s,encoding='utf-8')
p=Path('Docs/ALPHA_FRONTEND_RESOURCES.md');s=p.read_text(encoding='utf-8-sig').replace('Presentation transitions in0.85 seconds after world readiness.','After world readiness, a four-second 4–3–2–1 precedes combat; a side/elevated camera flies to gameplay in the final 1.5 seconds. Menu exit fades over 0.85 seconds.').replace('Numeric/code/error roles retain the readable fallback.','All combat HUD text, including numbers, uses Varose per latest user instruction. Room code/error roles retain the readable fallback.').replace('DOF radius fades out with the 0.85 s transition.','DOF fades during the final 1.5 seconds of the countdown.').replace('Varose-Regular.otf: short English labels.','Varose-Regular.otf: English menu labels and all in-game HUD labels/numbers.').replace('LiberationSans SDF: TMP Essentials, numbers/errors/code and fallback.','LiberationSans SDF: TMP Essentials, room codes/errors and missing-glyph fallback.')
s+='\n2026-09-06 17:08:19 UTC: updated AlphaFrontendPlay passed 1/1 with countdown, all-HUD Varose, local pause/resume/settings/end-match and repeated match entry. Use Elemental > UI > Select In-Game HUD Theme for fonts, size roles and colors. Pause uses real unscaled UI while local world time is zero; online pause suppression is prepared separately and does not stop the shared world.\n';p.write_text(s,encoding='utf-8')
for name in ['PROJECT_TECHNICAL_STATE.md','PROJECT_EXECUTION_TRACKER.md']:
 p=Path('Docs')/name;s=p.read_text(encoding='utf-8-sig');s+='\n## Alpha steering checkpoint — 2026-09-06 17:08 UTC\n\nSupersedes the earlier cadence-failure checkpoint: AlphaCadencePlay is now 2/2 PASS (16:51:11 UTC), player mean ratio 0.999438 and bot 0.999798 over ten cycles. Slope and visible turn-in-place remain open. AlphaFrontendPlay 1/1 PASS (17:08:19 UTC): 4–3–2–1, side/elevated framing with last 1.5-second gameplay blend, all-HUD Varose, local pause/resume/Settings/end-match. Profiles/scene saved. Wall bevel target 52.5 mm saved; latest sequential-repair/heavy-crush/Earth-body-filter requests in progress. Final build and Git commits pending; Stage 2 SDK and real-online acceptance remain pending. HEAD is still 1235579b36960e340211e52b81a17ae8dc5e32e2; no new commit claimed.\n';p.write_text(s,encoding='utf-8')
